---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    groups:
      bundler-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      npm-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: terraform
    directory: "/aws"
    schedule:
      interval: monthly
    groups:
      tf-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichoke"
    schedule:
      interval: monthly
    groups:
      tf-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichokeruby"
    schedule:
      interval: monthly
    groups:
      tf-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichoke-ruby"
    schedule:
      interval: monthly
    groups:
      tf-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/remote-state"
    schedule:
      interval: monthly
    groups:
      tf-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
