---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
