---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: terraform
    directory: "/aws"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichoke"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichokeruby"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/github-org-artichoke-ruby"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
  - package-ecosystem: terraform
    directory: "/remote-state"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
      - A-terraform
