name: Audit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  js:
    name: Audit JS Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Nodejs toolchain
        run: npm ci

      - name: npm audit
        run: npm audit
