---
name: Merge
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  blocked:
    name: Blocked by label
    runs-on: ubuntu-latest

    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "S-do-not-merge, S-wip"
