name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  terraform:
    name: Lint and format terraform
    runs-on: ubuntu-latest
    # https://www.terraform.io/docs/github-actions/getting-started.html
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "aws"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "remote-state"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Format markdown with prettier
        run: npx prettier --prose-wrap always --check '**/*.md'

      - name: Format YAML with prettier
        run: npx prettier --prose-wrap always --check '**/*.{yaml,yml}'
