---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  terraform:
    name: Lint and format terraform
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    # https://www.terraform.io/docs/github-actions/getting-started.html
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::447522982029:role/github-actions-artichoke-project-infrastructure-role
          aws-region: us-west-2

      - name: Show AWS caller identity
        run: aws sts get-caller-identity

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.x

      - name: "Format aws module"
        run: terraform -chdir=aws fmt -check -diff

      - name: "Initialize aws module"
        run: terraform -chdir=aws init

      - name: "Validate aws module"
        run: terraform -chdir=aws validate -no-color

      - name: "Format github module"
        run: terraform -chdir=github fmt -check -diff

      - name: "Initialize github module"
        run: terraform -chdir=github init

      - name: "Validate github module"
        run: terraform -chdir=github validate -no-color

      - name: "Format remote-state module"
        run: terraform -chdir=remote-state fmt -check -diff

      - name: "Initialize remote-state module"
        run: terraform -chdir=remote-state init

      - name: "Validate remote-state module"
        run: terraform -chdir=remote-state validate -no-color

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
